# Generated by Django 5.2.6 on 2025-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
